export const AI_MODELS = [
  { provider: 'ChatGPT', model: 'gpt-5.2', color: '#00a67e', logo: 'https://www.google.com/s2/favicons?sz=64&domain=openai.com' },
  { provider: 'ChatGPT', model: 'gpt-5', color: '#00a67e', logo: 'https://www.google.com/s2/favicons?sz=64&domain=openai.com' },
  { provider: 'ChatGPT', model: 'gpt-4o mini', color: '#00a67e', logo: 'https://www.google.com/s2/favicons?sz=64&domain=openai.com' },
  { provider: 'Gemini', model: 'gemini 3 pro', color: '#4285f4', logo: 'https://www.google.com/s2/favicons?sz=64&domain=google.com' },
  { provider: 'Gemini', model: 'gemini 2.5 flash', color: '#4285f4', logo: 'https://www.google.com/s2/favicons?sz=64&domain=google.com' },
  { provider: 'Gemini', model: 'gemini 2.0', color: '#4285f4', logo: 'https://www.google.com/s2/favicons?sz=64&domain=google.com' },
  { provider: 'Claude', model: 'claude opus 4.5', color: '#d4a574', logo: 'https://www.google.com/s2/favicons?sz=64&domain=anthropic.com' },
  { provider: 'Claude', model: 'claude sonnet 4.5', color: '#d4a574', logo: 'https://www.google.com/s2/favicons?sz=64&domain=anthropic.com' },
  { provider: 'Claude', model: 'claude Haiku 4.5', color: '#d4a574', logo: 'https://www.google.com/s2/favicons?sz=64&domain=anthropic.com' },
  { provider: 'Grok', model: 'Grok 4 fast', color: '#ffffff', logo: 'https://www.google.com/s2/favicons?sz=64&domain=x.ai' },
  { provider: 'Grok', model: 'Grok 3 mini', color: '#ffffff', logo: 'https://www.google.com/s2/favicons?sz=64&domain=x.ai' },
  { provider: 'Perplexity', model: 'Sonar pro', color: '#00bcd4', logo: 'https://www.google.com/s2/favicons?sz=64&domain=perplexity.ai' },
  { provider: 'Perplexity', model: 'Sonar Deep Research', color: '#00bcd4', logo: 'https://www.google.com/s2/favicons?sz=64&domain=perplexity.ai' },
];
